title: Mix of the Month Club 2021
logo: assets/logo.jpg
theme: jekyll-theme-minimal
plugins:
  - jemoji
# baseurl: https://hannahilea.github.io/2021-mix-of-the-month-club/
collections_dir: collections
collections:
  months:
    output: true
    sort_by: path
defaults:
-
  scope:
    path: ""
    type: "months"
  values:
    layout: "default"
