title: Mix of the Month Club 2021
logo: assets/logo.jpg
theme: jekyll-theme-minimal
plugins:
  - jemoji
collections_dir: collections
collections:
  months:
    output: true
    sort_by: path
defaults:
-
  scope:
    path: ""
    type: "months"
  values:
    layout: "default"
